### ISSUE TITLE
Glow effect

### ISSUE THREAD

**Issue by lasercar** [galaipa/SimpleRename#1]
Could you add a command to add / remove the glowing enchantment effect from an item?

**Comment by galaipa** [comment]
I will try to add it, I know I can do it using packets, but then the plugin would't be compatible with different minecraft versions.

**Comment by CloudeLecaw** [comment]
if its added wjat os wotj tje stranslations? is the current file realy up to date? and why all languages have so many different amount of lines...

**Comment by galaipa** [comment]
This is the latest release yes. There are some missing strings in some languages yes...
