### ISSUE TITLE
Anvil bug

### ISSUE THREAD

**Issue by Achent007** [galaipa/SimpleRename#11]
Hello,

When a player want to enchant item with book on the anvil, the items were removed and not given back to the player and he can't do the fusion. 
There is the log when the action is executed https://pastebin.com/V5Szy1VR

Server version : 1.14.3 paper-126 and after the bug is always present
SimpleRename version : 11.1

**Comment by Achent007** [comment]
And on the chat the player see : You don't have item on your hand

**Comment by galaipa** [comment]
According to my tests I think I have fixed this bug in v11.2. Please reopen the issue if you still have problems.
