### ISSUE TITLE
Naming 1.13 and 1.14 Items does not work

### ISSUE THREAD

**Issue by ShaneThePoole** [galaipa/SimpleRename#13]
When trying to name items from 1.13 or 1.14 with the /rename command, instead of naming the item the message _[SimpleRename] You need to have an item in your hand_ shows up, this message also shows up in anvils and causes the player to exit the anvil GUI making repairing or naming crossbows or tridents impossible

**Comment by MrWardy** [comment]
I get this issue too, I found it when trying to rename one of the new 1.14 banner patterns. A fix for this would be great, it's a pretty big bug.

**Comment by galaipa** [comment]
According to my tests I think I have fixed this bug in v11.2. Please reopen the issue if you still have problems.
