### ISSUE TITLE
Problemas con los GUI

### ISSUE THREAD

**Issue by Italoplcl** [galaipa/SimpleRename#26]
Al instalar el plugin en 1.14.4 me genera problema con plugins que tienen GUI.
En especifico con RedProtect y DailyRewards. El problema es que deja quitar cualquier item.
Eliminando SimpleRename se soluciona.

**Comment by galaipa** [comment]
Hola,
Muchas gracias por abrir el issue. Esta noche investigaré el problema. Mientras tanto puedes probar a poner `AnvilFeatures: false` en el `config.yml`. Si mis sospechas son ciertas eso debería de solucionar el problema.

**Comment by galaipa** [comment]
Muchisimas gracias otra vez por haber reportado el bug. Acabo de hacer release de la versión corregida.

He probado el plugin RedProtect y ahora todo parece funcionar correctamente. Si tienes cualquier problema no dudes en contactarme otra vez.

Un saludo

**Comment by Italoplcl** [comment]
Gracias a ti! Volveré a usar el plugin.
