### ISSUE TITLE
disappearing item when /sr getamount 128 or up

### ISSUE THREAD

**Issue by minejango2** [galaipa/SimpleRename#29]
/sr getamount 128 or up disappearing item
![ezgif-3-9403719ffc8b](https://user-images.githubusercontent.com/56389468/72584896-342f9080-392f-11ea-89f3-60f696783a9d.gif)

(I know that cannot set up to 128, but disapearing isn't good')

**Comment by galaipa** [comment]
Hello!
Thank you very much for reporting the bug! I was able to reproduce the bug in my computer. I will try to fix it as soon as possible. 

Although I update the plugin time to time, I haven't played the game for a while. Do you know if the max stack size is still 64? 

Also I would appreciate if you could tell me what SimpleRename and Minecraft version you are using.

Thanks!

**Comment by minejango2** [comment]
it can stack 127, but can't 128 or more.
I'm using 1.15.1, SimpleRename v12.2
