### ISSUE TITLE
korean language(glitched)

### ISSUE THREAD

**Issue by minejango2** [galaipa/SimpleRename#30]
translate to Korean
https://pastebin.com/FKeW25ZZ

But has a problem, this plugin needs yml Encording to UTF-8.
when it doesn't, 한국어 language doesn't appear correctly.

**Comment by galaipa** [comment]
I really appreciate the translation, I will investigate how I can fix the encoding problem.

**Comment by galaipa** [comment]
I copy/pasted the file to custom.yml and this are the messages I get in the game:
![irudia](https://user-images.githubusercontent.com/6819311/72933900-f97c8c80-3d62-11ea-9e53-c13f8e7c188b.png)

Excuse my ignorance, but are this messages correctly displayed? If not how should they be?
Thank you

**Comment by minejango2** [comment]
It displayed correctly! thanks for include my translation.

**Comment by minejango2** [comment]
+ ko_kr

**Comment by galaipa** [comment]
Thank you! Just included to the plugin. Will be available in next update
