### ISSUE TITLE
Disable glow on enchanted item

### ISSUE THREAD

**Issue by TheAgentRAINBOW** [galaipa/SimpleRename#35]
If possible, it would be a nice feature to be able to disable the glow effect on enchanted items. I read up a bit and it appears to be a tricky thing to do but would be great for like event items.

Example:
Enchant sword with sharpness, remove glow effect. At the moment this does not work, it will say "Success" but the glow remains.

**Comment by galaipa** [comment]
Hi!
First of all thank you for the suggestions but I am afraid that's not possible. I have investigated the issue, and it looks that the Bukkit/Spigot API doesn't allow to unglow an item without removing the enchantments. I will add an error message instead of the wrong "Success" string.
Thank you

**Comment by TheAgentRAINBOW** [comment]
Ok thank you. Will I close the issue?

**Comment by galaipa** [comment]
Yes, sorry. I couldn't make it work
