### ISSUE TITLE
korean language broked

### ISSUE THREAD

**Issue by minejango2** [galaipa/SimpleRename#36]
korean language(need UTF-8 language) broked
(+ reload is not a problem, still have problem even not reloaded)

**Comment by galaipa** [comment]
Hello,
Thank you for the report, and sorry for the late reply... But could you please give me some more details? What do you mean with breaking?

**Comment by minejango2** [comment]
![2020-04-13_09 28 09](https://user-images.githubusercontent.com/56389468/79083431-41f78500-7d69-11ea-9d52-674b26ea41a6.png)

korean language broked in chattng

**Comment by galaipa** [comment]
Sorry, I still don't understand what the problem is. What would be the expected behaviour there?

**Comment by galaipa** [comment]
Closing this issue because of lack of response. Please, feel free to reopen the issue if you still have problems.
