### ISSUE TITLE
Interferences with Silence Mobs plugin

### ISSUE THREAD

**Issue by galaipa** [galaipa/SimpleRename#42]
https://www.spigotmc.org/resources/silence-mobs.75749/

It could also be interfering with other similar plugins

**Comment by galaipa** [comment]
This is related to the &r formatting code the plugin adds by default.

**Comment by niqoar** [comment]
Hello! When you use a label with the name "Silence Me" on a mob, it should automatically be renamed to "Silenced" and not play any sounds. With "SimpleRename" installed, the mob is never renamed to "Silenced" so the plugin does not work.

Without "SimpleRename" it works correctly.

**Comment by niqoar** [comment]
Sorry, this was fixed with SimpleRename v13.0. I didn't realize I was on 12.2.

**Comment by galaipa** [comment]
No, it's not. A bug in v13.0 makes it work, but it won't if I release the new fixed version. The problem is the following:
By default when you rename an item, the game shows it in Italics. This doesn't look very nice, so a while a go I decided to add the &r formatting code at the beginning every time a renaming is performed. So, when you rename the name tag, the name is &rSilence Me, and the plugin doesn't detect it.
I think I can add configuration flag to disable this feature. What do you think?

**Comment by niqoar** [comment]
That sounds good!

**Comment by galaipa** [comment]
Fixed! I plan to release new version soon
