### ISSUE TITLE
Unable to blacklist items for lore only

### ISSUE THREAD

**Issue by ItsDed** [galaipa/SimpleRename#50]
I'm trying to figure out a way to prevent /relore on pickaxes and shovels while keeping /rename active.

Blacklisting diamond_pickaxe/shovel makes it so players can't /rename or /relore, but I want to make it so they can't /relore only.

Is there a feature that can distinguish between the two, or is it possible to have that added?

**Comment by galaipa** [comment]
Hello, did you try the `sr.[PERM].[MATERIAL]`  permission? I think you could deny the sr.lore.shovel (with the correct material name) permission to the users. Please let me know if it suits you.

**Comment by galaipa** [comment]
Closing this issue because of lack of response. Please, feel free to reopen the issue if you think it's necessary.
