### ISSUE TITLE
Dupe using Anvil

### ISSUE THREAD

**Issue by dotxzxc** [galaipa/SimpleRename#51]
Using anvil to rename an item beyond its max character limit will dupe the item by shift-clicking.
And also when you glow an item that has lore, the lore will be gone.

![duping](https://user-images.githubusercontent.com/29684878/93850051-e817c580-fcdf-11ea-9eda-9186d8386a68.gif)
![lore](https://user-images.githubusercontent.com/29684878/93850358-8015af00-fce0-11ea-9282-d65cb4ca1784.gif)

**Comment by galaipa** [comment]
Hello,
Thank you for reporting the bug! Unfortunately I'm very busy and I don't have much time for this, but I will try to fix it ASAP. Pull requests are welcome.

**Comment by galaipa** [comment]
Later than what I wanted, but I just pushed the fix to the bug. Thank you very much @dotxzxc for the report. I will publish the new jar in Spigot and Bukkit in the following days.
