### ISSUE TITLE
No way to re-show hidden flags.

### ISSUE THREAD

**Issue by MithicSpirit** [galaipa/SimpleRename#55]
There should be a command to undo `/sr hideflags`. This could either be `/sr showflags` or included in `/sr clear` (or both?).

**Comment by scarifyFX** [comment]
and to make stuff breakable again

**Comment by galaipa** [comment]
> There should be a command to undo `/sr hideflags`. This could either be `/sr showflags` or included in `/sr clear` (or both?).

Thank you very much for the [pull request](https://github.com/galaipa/SimpleRename/pull/56), we can continue the discussion there.



> and to make stuff breakable again

You can use `/sr breakable` for that. Please open an issue if you have any problem with it
