### ISSUE TITLE
1.13.1 - SimpleRename v10.7.5 Dislikes Trident

### ISSUE THREAD

**Issue by Roselynnn** [galaipa/SimpleRename#7]
I absolutely love your plugin and use it for absolutely everything, though it seems to dislike Tridents. I've had no other issues on 1.13.1 with it beyond this so far.
[https://gyazo.com/b807527097455c8cdc2bd47354f829c7](url)
I've seen someone in your reviews make a comment about this, but I did not see an issue relating to this posted in the Closed Issues tab, so I figured it would be alright to make a post about it.

**Comment by galaipa** [comment]
Hello,
Thank you very much for the kind review! SimpleRename v10.7.5 is intended for MC <= 1.12. Could you please try with v10.8 ?

**Comment by Roselynnn** [comment]
Will do. I'll try that, thank you! I'll get back to you on the results.

**Comment by Roselynnn** [comment]
Thank you for your response. Switching to 10.8 fixed the issue. I must have downloaded the most recent release without realizing it was not 10.8. Fantastic Plugin!

**Comment by bingenGalartza** [comment]
Thank you!
