### ISSUE TITLE
Anvil listener bug

### ISSUE THREAD

**Issue by TrollyLoki** [galaipa/SimpleRename#8]
Error: https://pastebin.com/vTbDXGLD
I was trying to combine two items in an anvil, I did not even touch the rename box, and I was suddenly kicked out of the anvil with this message: "[SimpleRename] You need to have an item in your hand" This makes it impossible to use an anvil for its intended purpose. Please fix.

**Comment by Wolfability** [comment]
I also have this problem. It occurs whenever we try to combine crossbows or or enchant tridents with books. Sometimes it deletes one of the items, but not always.
